# If you ever upgrade this image, watch out for bash being installed by default in newer alpine base images
FROM nginx:1.17-alpine

# Make sure the nc check fails in this container
RUN rm /usr/bin/nc

ADD nginx_on_8080.conf /etc/nginx/conf.d/default.conf
