FROM nginx:1.17-alpine

RUN apk add bash

# Make sure the /proc/net/tcp* check fails in this container
RUN rm /usr/bin/awk

# Make sure the nc check fails in this container
RUN rm /usr/bin/nc

ADD nginx_on_8080.conf /etc/nginx/conf.d/default.conf
