plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.testcontainers:testcontainers-ollama'
    testImplementation 'org.assertj:assertj-core:3.27.7'
    testImplementation 'ch.qos.logback:logback-classic:1.3.16'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.14.4'
    testImplementation 'io.rest-assured:rest-assured:6.0.1'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.14.4'
}

test {
    useJUnitPlatform()
}
