name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["type/bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: module
    attributes:
      label: Module
      description: Which Testcontainers module are you using?
      options:
        - Core
        - Azure
        - Cassandra
        - Clickhouse
        - Couchbase
        - DB2
        - Dynalite
        - Elasticsearch
        - GCloud
        - HiveMQ
        - InfluxDB
        - K3S
        - Kafka
        - LocalStack
        - MariaDB
        - MockServer
        - MongoDB
        - MSSQLServer
        - MySQL
        - Neo4j
        - NGINX
        - Oracle-XE
        - OrientDB
        - PostgreSQL
        - Presto
        - Pulsar
        - RabbitMQ
        - Selenium
        - Solr
        - ToxiProxy
        - Trino
        - Vault
    validations:
      required: true
  - type: input
    id: tc-version
    attributes:
      label: Testcontainers version
      description: Which Testcontainers version are you using?
      placeholder: ex. 1.17.2
    validations:
      required: true
  - type: dropdown
    id: latest-version
    attributes:
      label: Using the latest Testcontainers version?
      description: If you are not using the latest version, can you update your project and try to reproduce the issue? Is it still happening?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
  - type: textarea
    id: docker-version
    attributes:
      label: Docker version
      description: Please run `docker version` and copy and paste the output into this field.
      render: markdown
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Provide the context and the expected result.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. The content will be automatically formatted as code, so no need for backticks.
      render: shell
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: |
        Any links or references to have more context about the issue.

        Tip: You can attach a minimal sample project to reproduce the issue or log files by clicking this area to highlight it and then dragging files in.
