name: Enhancement
description: Suggest an enhancement
title: "[Enhancement]: "
labels: ["type/enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Before submitting an `enhancement`, please make sure there is no existing enhancement for the one you are requesting and it has been discussed with the team via [discussions](https://github.com/testcontainers/testcontainers-java/discussions) or Slack. If so, please provide the following information:
  - type: dropdown
    id: module
    attributes:
      label: Module
      description: For which Testcontainers module does the enhancement proposal apply?
      options:
        - Core
        - ActiveMQ
        - Azure
        - Cassandra
        - ChromaDB
        - Clickhouse
        - CockroachDB
        - Consul
        - Couchbase
        - CrateDB
        - Databend
        - DB2
        - Dynalite
        - Elasticsearch
        - GCloud
        - Grafana
        - HiveMQ
        - InfluxDB
        - K3S
        - K6
        - Kafka
        - LocalStack
        - MariaDB
        - Milvus
        - MinIO
        - MockServer
        - MongoDB
        - MSSQLServer
        - MySQL
        - Neo4j
        - NGINX
        - OceanBase
        - Ollama
        - OpenFGA
        - Oracle Free
        - Oracle XE
        - OrientDB
        - Pinecone
        - PostgreSQL
        - Presto
        - Pulsar
        - Qdrant
        - QuestDB
        - RabbitMQ
        - Redpanda
        - ScyllaDB
        - Selenium
        - Solace
        - Solr
        - TiDB
        - Timeplus
        - ToxiProxy
        - Trino
        - Typesense
        - Vault
        - Weaviate
        - YugabyteDB
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: What should be improved? What are the limitations of the current implications that would be solved by the proposal?
    validations:
      required: true
