plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.assertj:assertj-core:3.27.7'
    testImplementation 'org.neo4j.driver:neo4j-java-driver:4.4.27'
    testImplementation 'org.testcontainers:testcontainers-neo4j'
    testImplementation 'org.testcontainers:testcontainers-junit-jupiter'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.14.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.14.4'
}

test {
	useJUnitPlatform()
}
