name: Set up Java
description: Sets up Java version
inputs:
  java-version:
    description: 'The Java version to set up'
    required: true
    default: '17'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: temurin
