FROM alpine:3.14@sha256:0f2d5c38dd7a4f4f733e688e3a6733cb5ab1ac6e3cb4603a5dd564e5bfb80eed AS builder

WORKDIR /my-files

RUN echo 'Hello World' > hello.txt

FROM alpine:3.14

COPY --from=builder /my-files/hello.txt hello.txt
